name: Docker CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Create Firebase service account file
      run: echo '${{ secrets.GO_JSON }}' > go.json
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ 'docker.io' }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/php:latest,${{ secrets.DOCKER_USERNAME }}/php:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |

          echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${{'docker.io' }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          cd footballnewsapi
          git stash
          git pull origin main
          sudo chmod 755 docker/entrypoint.sh
          docker compose down | true
          docker rmi ${{ secrets.DOCKER_USERNAME }}/php:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/php:latest
          docker compose up -d
          # docker compose exec api composer update
          # docker compose exec api php artisan migrate
          docker system prune -a -f
          docker compose up -d

